### ISSUE TITLE
Not reading users with spaces in the name

### ISSUE THREAD

**Issue by mroe451** [TheGogy/cw-esp#11]
Error:

NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/matthewroe/Downloads/cw-esp/main.py", line 63, in <module>
    microphoneThread = MicrophoneThread()
  File "/Users/matthewroe/Downloads/cw-esp/main.py", line 17, in __init__
    self.window = SubtitleWindow()
  File "/Users/matthewroe/Downloads/cw-esp/SubtitleWindow.py", line 16, in __init__
    self.css = Profiles.getCurrentUserCSS()
  File "/Users/matthewroe/Downloads/cw-esp/Profiles.py", line 10, in getCurrentUserCSS
    with open(Profiles.getUserPath(Profiles.getCurrentUser()), "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/matthewroe/Downloads/cw-esp/Users/MR Test 1.css'

**Comment by box1273002** [comment]
Could not reproduce the concenus is that it was incorrectly installed
